
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.166.233.152:3306/eat?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: eating
    password: eatingdoit

  mail:
    host: smtp.gmail.com
    port: 587
    username: yevin2001@gmail.com # 앱 비밀번호를 발급받은 구글 계정
    password: bwah kiwj bbti htio # 발급받은 앱 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true